apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: britepulse-console
  labels:
    app: britepulse
    component: console
spec:
  template:
    metadata:
      annotations:
        # Static frontend can scale to zero
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "200"
    spec:
      containerConcurrency: 250
      timeoutSeconds: 60
      containers:
        - image: gcr.io/${PROJECT_ID}/britepulse-console:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: PORT
              value: "8080"
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
